### ISSUE TITLE
Issue: Mistakingly parses bracketed part of a value as section title

### ISSUE THREAD

**Issue by SquareByte** [ZachPerkitny/configparser#11]
The current implementation (0.3.9) parses a file like

```ini
[sec]
key = [value]
```
as a config with two empty sections `'sec'` and `'value'`. The key `'key'` is lost all together.

**Comment by ZachPerkitny** [comment]
Yup, was able to reproduce this, I can just modify the regular expression for section by adding a `^` and it won't match key = [value]

**Comment by ZachPerkitny** [comment]
It's been published (0.3.10), you can also do something like `[key] = [value]` now

**Comment by ZachPerkitny** [comment]
Also, it passes all the tests, there's something wrong with circleci, and I'm feeling a bit lazy today.
