### ISSUE TITLE
Run mkdir if filepath is non existent

### ISSUE THREAD

**Issue by IJustDev** [ZachPerkitny/configparser#3]
Let's assume we are in a folder with the path `/home/development/codegenerator` and want to create a file called `config.ini` in the folder `/home/development/codegenerator/out/configuration/` and both of these folders are non existent. You'll receive an error because you need to create these folders by yourself.
I would suggest automatically creating these folders in future versions.

**Comment by ZachPerkitny** [comment]
Hey,

I've just added it, I just have to fix my circle configuration, and then I'll publish it to npm :)

**Comment by ZachPerkitny** [comment]
I just published v0.3.6,

the `write` and `writeAsync` methods take a boolean as the second parameter which is used to indicate whether missing directories should be created (defaults to false).

So just run `config.write('/home/development/codegenerator/out/configuration/config.ini', true);`.

**Comment by IJustDev** [comment]
It works.

Thank you pretty much!
